#! /usr/bin/env bash

PS3="메뉴를 선택하세요: "

options=("인사하기" "현재 시간 보기" "종료")
select opt in "${options[@]}"; do
    case $opt in
    "인사하기")
        echo "안녕하세요!"
        ;;
    "현재 시간 보기")
        echo "현재 시간: $(date)"
        ;;
    "종료")
        echo "프로그램을 종료합니다."
        break
        ;;
    *) echo "잘못된 옵션입니다. 다시 시도하세요." ;;
    esac
done
